apiVersion: app.k8s.io/v1beta1
kind: Application
metadata:
  annotations:
    argocd.argoproj.io/compare-options: IgnoreExtraneous
  name: deploy-rhacm-geo-hub-policygenerator
  namespace: rhacm-applications
spec:
  componentKinds:
    - group: apps.open-cluster-management.io
      kind: Subscription
  selector:
    matchExpressions:
      - key: app
        operator: In
        values:
          - deploy-rhacm-geo-hub-policygenerator
# ---
# apiVersion: apps.open-cluster-management.io/v1
# kind: Channel
# metadata:
#   annotations:
#     argocd.argoproj.io/compare-options: IgnoreExtraneous
#     apps.open-cluster-management.io/reconcile-rate: medium
#   name: githubcom-gskumar1010-multiverse-of-multicluster-madness
#   namespace: rhacm-channels
# spec:
#   type: Git
#   pathname: 'https://github.com/gskumar1010/multiverse-of-multicluster-madness'
---
apiVersion: apps.open-cluster-management.io/v1
kind: Subscription
metadata:
  annotations:
    argocd.argoproj.io/compare-options: IgnoreExtraneous
    apps.open-cluster-management.io/git-branch: main
    apps.open-cluster-management.io/git-path: rhacm/policy-generators/deploy-rhacm-hub
    apps.open-cluster-management.io/reconcile-option: merge
  labels:
    app: deploy-rhacm-geo-hub-policygenerator
  name: deploy-rhacm-geo-hub-policygenerator
  namespace: rhacm-applications
spec:
  channel: rhacm-channels/githubcom-gskumar1010-multiverse-of-multicluster-madness
  placement:
    placementRef:
      kind: PlacementRule
      name: hub-of-hubs-clusters
