---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - manifests/00_namespace.yml
  - manifests/11_bookinfo.yml
  - manifests/12_bookinfo-gateway.yml
  - manifests/13_bookinfo-destination-rule-all.yml

namespace: bookinfo