---
apiVersion: apps.open-cluster-management.io/v1
kind: Subscription
metadata:
  annotations:
    apps.open-cluster-management.io/git-branch: main
    apps.open-cluster-management.io/git-path: applications/omg-shoes/manifests
    apps.open-cluster-management.io/reconcile-option: merge
  labels:
    app: omg-shoes
  name: omg-shoes-subscription
  namespace: rhacm-applications
spec:
  channel: rhacm-channels/githubcom-gskumar1010-multiverse-of-multicluster-madness
  placement:
    placementRef:
      kind: PlacementRule
      name: omg-shoes-placement
  #timewindow:
  #  windowtype: active # active | blocked
  #  location: "America/New_York"
  #  daysofweek: ["Monday","Tuesday","Wednesday","Thursday","Friday"]
  #  hours:
  #    - start: "12:00AM"
  #      end: "11:30PM"
