---
kind: ExternalSecret
apiVersion: external-secrets.io/v1beta1
metadata:
  #annotations:
    #acme.org/sha: 1234
  #labels:
    #acme.org/owned-by: q-team
  name: repo-mvomcm
  namespace: openshift-gitops
spec:
  refreshInterval: 10m
  secretStoreRef:
    kind: ClusterSecretStore
    name: hoh-vault
  data:
    - secretKey: gitusername
      remoteRef:
        key: hoh-git-reader
        property: git_username
    - secretKey: gitpassword
      remoteRef:
        key: hoh-git-reader
        property: git_password
  target:
    creationPolicy: Owner
    deletionPolicy: Retain
    name: repo-mvomcm
    template:
      type: Opaque
      data:
        insecure: "true"
        url: https://github.com/gskumar1010/multiverse-of-multicluster-madness
        type: git
        project: hub-of-hubs-cluster-apps
        name: mvomcm
        username: "{{ .gitusername | toString }}"
        password: "{{ .gitpassword | toString }}"
      metadata:
        labels:
          argocd.argoproj.io/secret-type: repository
        annotations:
          managed-by: argocd.argoproj.io
    #template:
    #  data:
    #    config.yml: |
    #      endpoints:
    #      - https://{{ .data.user }}:{{ .data.password }}@api.exmaple.com
    #  metadata:
    #    annotations: {}
    #    labels: {}
    #  templateFrom:
    #    - configMap:
    #        items:
    #          - key: alertmanager.yaml
    #        name: alertmanager
    #  type: kubernetes.io/dockerconfigjson
