apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: global-config-rbac
  namespace: openshift-gitops
spec:
  project: default
  source:
    repoURL: 'https://github.com/gskumar1010/multiverse-of-multicluster-madness'
    targetRevision: HEAD
    ## Path is the repo directory that containers the cluster(s) configuration and deployment manifests
    path: manifests/global-rbac
    ## Enable recursive sub-directory search to enable management of multiple cluster from this single Application
    directory:
      recurse: true
  destination:
    server: "https://kubernetes.default.svc"
  syncPolicy:
    automated:
      #prune: true
      allowEmpty: true
      #selfHeal: false # overrides changes made on the cluster that drift from git state
    syncOptions:
      - CreateNamespace=true